
// Objective-C API for talking to the following Go packages
//
//	github.com/cmanus/nashgophers/gonashgopher
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gonashgopher_FRAMEWORK_H__
#define __Gonashgopher_FRAMEWORK_H__

#include "Gonashgopher.objc.h"
#include "Universe.objc.h"

#endif
