// Objective-C API for talking to github.com/cmanus/nashgophers/gonashgopher Go package.
//   gobind -lang=objc github.com/cmanus/nashgophers/gonashgopher
//
// File is generated by gobind. Do not edit.

#ifndef __Gonashgopher_H__
#define __Gonashgopher_H__

@import Foundation;
#include "Universe.objc.h"


@protocol GonashgopherLogger;
@class GonashgopherLogger;

@protocol GonashgopherLogger <NSObject>
- (void)log:(NSString*)message;
@end

FOUNDATION_EXPORT void GonashgopherHelloWorld(id<GonashgopherLogger> logger);

@class GonashgopherLogger;

@interface GonashgopherLogger : NSObject <goSeqRefInterface, GonashgopherLogger> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)log:(NSString*)message;
@end

#endif
